### ISSUE TITLE
Injector "runtime error" when pod has 'anyuid' SCC permission

### ISSUE THREAD

**Issue by bejoycalias** [openlab-red/hashicorp-vault-for-openshift#29]
I have a deployment which needs to run with 'anyuid' permission. So I add the service account to 'anyuid' SCC (oc adm policy add-scc-to-user anyuid -z default -n mynamespace). When I deploy this with vault injection annotations, the deployment never works. If I look into the event logs, I see this error

10s         Warning   FailedCreate        replicaset/vault-agent-demo-5fc7cb5b6b   Error creating: Internal error occurred: failed calling webhook "vault.hashicorp.com": Post https://vault-agent-injector-svc.appopsmgmt.svc:443/mutate?timeout=5s: EOF

And the vault-injector pod has these logs 

2020-06-03T05:57:07.371Z [INFO]  handler: Request received: Method=POST URL=/mutate?timeout=5s
2020/06/03 05:57:07 http: panic serving 172.30.79.135:51412: runtime error: invalid memory address or nil pointer dereference
goroutine 707 [running]:
net/http.(*conn).serve.func1(0xc0003fa6e0)
        /usr/local/go/src/net/http/server.go:1767 +0x139
panic(0x1111380, 0x1c04cf0)
        /usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/hashicorp/vault-k8s/agent-inject/agent.Init(0xc00007f500, 0xc000042049, 0xb, 0xc000044018, 0x21, 0x1267c73, 0xf, 0xc00050a380, 0xb, 0x0, ...)
        /Users/mmascia/dev/lab/go/src/github.com/hashicorp/vault-k8s/agent-inject/agent/annotations.go:253 +0x550
github.com/hashicorp/vault-k8s/agent-inject.(*Handler).Mutate(0xc000313500, 0xc0001f2f20, 0xb00)
        /Users/mmascia/dev/lab/go/src/github.com/hashicorp/vault-k8s/agent-inject/handler.go:151 +0x83f
github.com/hashicorp/vault-k8s/agent-inject.(*Handler).Handle(0xc000313500, 0x1408d20, 0xc0001969a0, 0xc000439400)
        /Users/mmascia/dev/lab/go/src/github.com/hashicorp/vault-k8s/agent-inject/handler.go:87 +0x721
net/http.HandlerFunc.ServeHTTP(0xc0002c5c50, 0x1408d20, 0xc0001969a0, 0xc000439400)
        /usr/local/go/src/net/http/server.go:2007 +0x44
net/http.(*ServeMux).ServeHTTP(0xc000302700, 0x1408d20, 0xc0001969a0, 0xc000439400)
        /usr/local/go/src/net/http/server.go:2387 +0x1bd
net/http.serverHandler.ServeHTTP(0xc000197260, 0x1408d20, 0xc0001969a0, 0xc000439400)
        /usr/local/go/src/net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc0003fa6e0, 0x140c360, 0xc0000d8f00)
        /usr/local/go/src/net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2928 +0x384

If I remove my service account from 'anyuid' SCC (oc adm policy remove-scc-from-user anyuid system:serviceaccount:mynamespace:default) and if I deploy again, it works perfectly fine and I am able to see the injected secrets. (even though my application doesn't work since it needs 'anyuid' permissions)

I tried creating a new service account instead of using the 'default' one, but the behaviour is exactly same. Injector fails if the service account is part of 'anyuid' SCC. Is this a known issue, any fix or workaround?

OpenShift 4.3.19
Injector image: openlabred/vault-k8s:0.3.1
Vault image: vault:1.4.1

**Comment by eye0fra** [comment]
Hi @bejoycalias , it seems that agent is failing to inizialize. Can you show me the annotations? Moreover, yesterday hashicorp officially release a new version of vault-k8s which contains the run as user functionality based on this project.  https://github.com/hashicorp/vault-k8s/blob/master/CHANGELOG.md#040-june-2-2020

**Comment by bejoycalias** [comment]
@eye0fra This is my complete deployment yaml

```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-agent-demo
  labels:
    app: vault-agent-demo
spec:
  selector:
    matchLabels:
      app: vault-agent-demo
  replicas: 1
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-secret-aws.creds: aws/creds/expsqd-ref-impl-4-3-sns
        vault.hashicorp.com/ca-key: /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt
        vault.hashicorp.com/role: ref-impl-4-3-role
        vault.hashicorp.com/secret-volume-path: /tmp/bejoy
      labels:
        app: vault-agent-demo
    spec:
      containers:
      - name: vault-agent-demo
        image: jweissig/app:0.0.1
```
